---
title: "Precourse"
subtitle: "These are steps to be completed before the workshop"
date: ""
toc: true
number-sections: false
sidebar: false
code-tools: false
format: html
---

## {{< fa server >}} Installations

#### {{< fa brands r-project >}} R

 Download and install the latest version of R from [r-project.org](https://cloud.r-project.org/).

#### {{< fa solid pen-to-square >}} IDE

Install [RStudio](https://posit.co/download/rstudio-desktop/). RStudio provides you with tools like code editor with highlighting, project management, version control, package building, debugger, profiler and more. [Visual Studio code](https://code.visualstudio.com/docs/setup/setup-overview) is another good alternative to RStudio.

#### {{< fa solid book-open-reader >}} Quarto

 Download and install the latest version of Quarto from [quarto.org](https://quarto.org/docs/get-started/).

#### {{< fa solid cube >}} R packages

Install all the R packages necessary for this course by opening an `R terminal` either in Rstudio or VScode and pasting the following command:

```{r,eval=FALSE,block.title=TRUE}

install.packages(c("cowplot","crosstalk","dplyr","DT","gganimate","ggiraph",
                    "ggplot2","ggpubr","ggrepel","ggthemes","grid","gridExtra",
                    "gt", "kableExtra","leaflet","palmerpenguins","patchwork",
                    "pheatmap","plotly","reshape2","scales","Seurat","shiny",
                    "tidyr","tidyverse","wesanderson"), dependencies = TRUE)

```

::: {.callout-tip}
To make sure that the installations went well, we will try to make a quick plot using the packages you just installed. In this plot, we try to see if there is correlation plot between `BMI` and average `no.of steps` taken by some volunteers per day. The data and the code for plotting is available [here](https://github.com/NBISweden/workshop-data-visualization-r/raw/main/data/Installation_check/packages_check.zip). Just `render` or `preview` the `installation_check.qmd` file in RStudio or VScode. and you should see the correlation plot, if all the packages are installed properly. 
:::

:::{.callout-caution icon="false"}
### {{< fa solid file-arrow-down >}} Download course files

Please download all the necessary files from [here](https://nbisweden.github.io/workshop-data-visualization-r/2505/topics/lab_download.html) and make sure that the directory tree looks similar to the one displayed in that page.

:::

## {{< fa brands markdown >}} HackMD

We will use the online note-keeping document from HackMD for our questions. Please click [here](https://hackmd.io/@g4wu57tQRzSqYwnAPalt0Q/HJbAkaTXq) to see the notebook. We would appreciate it a lot if you could write your questions and feedback here, so that all participants can learn from each other.

## {{< fa book >}} Preparations

To prepare for the course, you can follow one of the links below to warm up your skills necessary for the course.

::: {.callout-tip}
 - Beginner-level: [Basic warm-up exercises in R](https://immuntech.github.io/Bioinformatics_Workshop_ImmTech/Data/2019-10-15/R_exercise_Lokesh.html)
 - Advanced-level: [ggplot warm-up](https://nbisweden.github.io/workshop-data-visualization-r/2210/home_content.html#4_Main_lab)
:::

:::{.callout-tip icon="false" collapse="true"}
## {{< fa brands docker >}} Docker

If you are more familiar with using `Docker`, all the tools necessary for the course are available as a Docker image. You can pull the image using the following command:

```
docker pull ghcr.io/nbisweden/workshop-adv-data-viz:latest
```

If you would like to try to install `Docker` and give it a try, please follow the instructions [here](other/docker.html)

### {{< fa brands microsoft >}} Visual Studio code

The best and most efficient way to work with the Docker image is with `VScode` and the extension `Dev Containers`. Similar to `RStudio` or `Posit`, `VScode` is an IDE maintained by Microsoft and it is quite efficient and robust for all Operating systems. 

 - To install VScode, follow the instructions [here](https://code.visualstudio.com/docs/setup/setup-overview)
 - After successful installation of VScode and Docker, you can install the `Dev Containers` extension for VScode from [here](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers)
 - Download the `Dev Container` file from [here](https://github.com/NBISweden/workshop-data-visualization-r/raw/main/dev-container-file/.devcontainer.json) *Make sure that all the course related files are in the same place as this `.devcontainer.json` hidden file*
 - Then in `VScode`, press `Ctrl+Shift+P` (`Cmd+Shift+P` for Mac users) followed by  `Dev Containers: Open Folder in Container` to select the folder where you have all the files or `Dev Containers: Reopen in Container`, if you are already on VScode in the same directory.
 - Now, if everything worked fine, a new window shoudl appear inside the `Advanced Data Visualization` container.

:::