---
title: "Syllabus"
subtitle: "Syllabus, learning outcomes and entry requirements"
date: ""
toc: false
number-sections: false
sidebar: false
format: html
---

::: {.panel-tabset}

## Syllabus

The syllabus for this workshop are as follows.

- Advanced level
  - Using the language of graphics: ggplot2
  - Basic and advanced plotting in ggplot2
  - Single-cell data visualizations with Seurat
  - Quarto notebooks and reports
  - Dynamic plotting with Quarto
  - Interactive web apps with Shiny

- Beginner level
  - Handle data in R for visualizations
  - Apply ggplot grammar to get publication-grade plots
  - Combine different data and/or different plots
  - PCA, Heatmaps, Phylogenetic trees and Maps

## Learning outcomes

After this workshop you should be able to:

- Advanced level
  - Handle data in R for visualizations
  - Familiarize with ggplot2 functions and techniques at adavanced level
  - Combine different data and/or different plots that are of publication-ready
  - Create interactive documents with Quarto for data exploration and analysis
  - Write your own simple Shiny app in R

- Beginner level
  - Handle data in R for visualizations
  - Apply the grammar efficiently in ggplot to obtain the desired plot
  - Combine different data and/or different plots that are of publication-grade

## Entry requirements

- Familiarity with R and R Studio
- Plotting using standard R graphics
- Participants are expected to use their own computers with pre-installed R, R Studio and different R packages (detailed instructions will be given upon acceptance).


:::
