---
title: "Package installation check"
author: "`r paste0('<b>Lokesh Mano</b> • ',format(Sys.time(), '%d-%b-%Y'))`"
output: 
  rmarkdown::html_document:
    toc: false
    toc_float: false
    smart: true
    number_sections: false
    highlight: tango
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
x <- c("ggplot2","tidyverse","ggmap","pheatmap","devtools","cowplot",
       "reshape2", "dplyr", "wesanderson", "scales", "ggthemes", "ggrepel", 
       "ggpubr", "gridExtra", "ggtree", "treeio", "shiny", "gganimate", "shinythemes",
       "rsconnect", "colourpicker")
for (i in x){
 library(i, character.only = TRUE)
}
```


# Package installations worked!

### And here is the correlation test for the Toy dataset


```{r, message=FALSE, warning=FALSE, echo=FALSE}
toy <- read.csv("toy.csv", header = T, stringsAsFactors = F, row.names = 1)
p1 <- ggplot(toy,aes(Steps, BMI, color = Sex)) + geom_point(size = 0.25) + theme_bw() + theme(panel.grid = element_blank()) 
gc_text <- paste("If you don't recognize the correlation you see in the figure above,", 
                 "I would highly recommend you to read the following paper ;)", sep = " ")
tex1 <- ggparagraph(text = gc_text, size = 11, color = "black")
gc_text2 <- "Yanai, I., Lercher, M. A hypothesis is a liability. Genome Biol 21, 231 (2020)."
tex2 <- ggparagraph(text = gc_text2, size = 14, face = "bold", color = "blue")
ggarrange(p1, tex1, tex2, nrow = 3, heights = c(8, 1, 1))

```